title: Defense Of Democracy
subheads:
    - "Advocates · Allies · Americans"

email: email@example.com
description: >-
    A brief description of your site
baseurl: ""
url: "https://links.democracy.org/"

# uncomment and fill in any social IDs you want linked from the top of your page

email: "info@defenseofdemocracy.org"
tiktok_username: "_dofd"
# github_username: "my_github_username"
youtube_channel_id: "UCwMRXVPwN8F7StGy77Lvf_Q"
facebook_username: "defenseofdemocracy1"
instagram_username: "dofdnational"
threads_username: "dofdnational"
telephone_number: "845-208-9846"
# pinterest_username: "my_pinterest_username"
twitter_username: "_dofd"
bluesky_username: "defenseofdemocracy"
github_username: false

# uncomment for plausible.io analytics, should match the "url" above
# plausible_io: example.com

# uncomment to add your google analytics
# google_analytics: UA-NNNNNNNN-N

# Build settings
theme: jekyll-theme-linky
plugins:
    - jekyll-feed

exclude:
    - VERSION
    - bin
    - linky.gemspec
    - netlify.toml

linky:
    body_background: "#2d598f"
    body_foreground: "#fff"
    button_background: "#ebead9"
    button_foreground: "#030303"
    social_button_color: "#ffffff"

collections:
    - links

# tell the jekyll-feed plugin to include the links collection
feed:
    collections:
        - links
